### ISSUE TITLE
Should we add the type of API/data formats to the descriptions?

### ISSUE THREAD

**Issue by daneelrakow** [n0shake/Public-APIs#22]
I think it would be a good idea to add some more info, stuff like data type, API type, if it's free or a trial/paid service, if you need a key or don't, etc...

Example:

SampleAPI - an api to do x, y, and z [REST, JSON, Free]

**Comment by 007Cat24** [comment]
Yeah, that would be helpful - however, we should highlight APIs with a dev tier.

**Comment by abhishekbanthia** [comment]
That's a great suggestion. I have already tried to include info regarding cost wherever possible. I'll include this in the Contributing Guidelines.

**Comment by daneelrakow** [comment]
We would need a guideline for it. 

J for JSON
X for XML
REST for a REST api, stuff like that.

**Comment by skemb321** [comment]
This is a nice suggestion! I just saw this repo now and it looks awesome! :clinking_glasses:

**Comment by Joshfindit** [comment]
This discussion sounds like it could end up with an API for Public-APIs

**Comment by n0shake** [comment]
I'm going to close this out since there hasn't been any activity recently. Happy to review any PRs that adds more info or even builds an API 😃
