### ISSUE TITLE
Live version of website is broken

### ISSUE THREAD

**Issue by pilotkid** [n0shake/Public-APIs#471]
It doesn't look like the tables are being formatted correctly on the GH pages version
![image](https://user-images.githubusercontent.com/6385285/143802125-f9ad7a5d-4d2b-4db2-a49e-8f85046cd81f.png)

**Comment by n0shake** [comment]
Thanks for surfacing this! There are no active plans to maintain the GH Pages version of the repo as of now; Happy to accept PRs though :)
